use_frameworks!

platform :ios, '10.0'

target 'YDToolBox_Example' do
  pod 'YDToolBox', :path => '../'

  target 'YDToolBox_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
